### ISSUE TITLE
Coercion not working with data specs other than "string?"

### ISSUE THREAD

**Issue by ElChache** [metosin/reitit#145] opened 2018-09-19 22:02 UTC
I tried the example in [Data-specs](https://metosin.github.io/reitit/coercion/data_spec_coercion.html), but when I call the function match-by-path-and-coerce! I get the error:
`Error: Request coercion failed: #reitit.coercion.CoercionError{:spec #spec-tools.core.Spec{:spec #object[cljs.spec.alpha.t_cljs$spec$alpha32650], :form (cljs.spec.alpha/keys :req-un [:$spec2/company :$spec2/user-id]), :type :map, :keys #{:company :user-id}, :keys/req #{:company :user-id}}, :problems ({:path [:user-id], :pred spec-tools.form/int?, :val "123", :via [:$spec2/user-id], :in [:user-id]})}
`
But if I change the user-id spec from int? to string?, then it works as expected.

I am using clojure 1.10.0-alpha4 and clojurescript 1.10.339

**Comment by valerauko** [comment] 2018-09-22 13:43
I'm having a similar problem with an optional parameter:

Relevant piece:
```
             :parameters {:query {(ds/opt :page) pos-int?}}
```
Error:
```
server       | In: [:parameters :query #spec_tools.data_spec.OptionalKey{:k :page} 0] val: #spec_tools.data_spec.OptionalKey{:k :page} fails spec: :reitit.core.coercion/kw-map at: [:parameters :query :map 0] predicate: keyword?
server       | In: [:parameters :query] val: {#spec_tools.data_spec.OptionalKey{:k :page} #object[clojure.core$pos_int_QMARK_ 0x3b7fdef9 "clojure.core$pos_int_QMARK_@3b7fdef9"]} fails spec: :reitit.core.coercion/kw-map at: [:parameters :query :spec] predicate: spec?
```

**Comment by ikitommi** [comment] 2018-09-22 14:27
for the latter, it works:

```clj
(ns user
  (:require [reitit.ring :as ring]
            [reitit.ring.coercion :as rrc]
            [reitit.coercion.spec :as spec]
            [spec-tools.data-spec :as ds]))

(def app
  (ring/ring-handler
    (ring/router
      ["/plus"
       {:get {:middleware [rrc/coerce-request-middleware]
              :coercion spec/coercion
              :parameters {:query {(ds/opt :page) pos-int?}}
              :handler (fn [{{{:keys [page]} :query} :parameters}]
                         {:status 200, :body (+ page 100)})}}])))

(app {:request-method :get, :uri "/plus", :query-params {"page" "1"}})
; {:status 200, :body 101}
```

**Comment by ikitommi** [comment] 2018-09-22 18:33
@ElChache added a test that the example works. Tested on clojure 1.9.0, 1.10.0-alpha6 and clojurescript 1.10.339 (Chrome, Node & Advanced).

**Comment by dancek** [comment] 2018-09-26 07:14
I've got something similar, and weirdly the issue only manifests itself on uberjars built on our Jenkins server. If I build an uberjar locally and deploy it to the same server, everything works just fine. Also works in REPLs  etc.

Might be someting stupid I've done, sorry if it's that. Still, this doesn't make sense to me so I'm posting in case it's a bug in reitit or spec-tools.
 
The error message I get is `Can't invoke spec with a non-function predicate` and the data for the ExceptionInfo (`(ex-data my-ex-info)`) I get is as follows:
```
{:spec #Spec{:form (clojure.spec.alpha/keys :req-un [:$spec6066/email :$spec6066/password]), :type :map, :keys #{:email :password}, :keys/req #{:email :password}}}
```

The parameter spec I'm using:
```
                     :parameters {:body {:email string?, :password string?}}
```

And the `ring/router` config:
```
      {:data {:coercion   reitit.coercion.spec/coercion
              :muuntaja   m/instance
              :middleware (concat [error-format-middleware
                                   ring.middleware.params/wrap-params
                                   ring.middleware.cookies/wrap-cookies
                                   muuntaja/format-middleware
                                   rrc/coerce-exceptions-middleware
                                   rrc/coerce-response-middleware
                                   rrc/coerce-request-middleware]
                                  middlewares)}})
```

The full stack trace:
```
clojure.lang.ExceptionInfo: Can't invoke spec with a non-function predicate: spec_tools.core.Spec@c81fac17
	at clojure.core$ex_info.invokeStatic(core.clj:4739) ~[app/:na]
	at clojure.core$ex_info.invoke(core.clj:4739) ~[app/:na]
	at spec_tools.core$fail_on_invoke.invokeStatic(core.cljc:207) ~[app/:na]
	at spec_tools.core$fail_on_invoke.invoke(core.cljc:205) ~[app/:na]
	at spec_tools.core.Spec.invoke(core.cljc:275) ~[app/:na]
	at clojure.spec.alpha$spec_impl$reify__4053.conform_STAR_(alpha.clj:875) ~[na:na]
	at clojure.spec.alpha$conform.invokeStatic(alpha.clj:150) ~[app/:na]
	at clojure.spec.alpha$conform.invoke(alpha.clj:146) ~[app/:na]
	at spec_tools.core$conform.invokeStatic(core.cljc:146) ~[app/:na]
	at spec_tools.core$conform.invoke(core.cljc:139) ~[app/:na]
	at reitit.coercion.spec$create$reify__9623$fn__9671.invoke(spec.cljc:125) ~[app/:na]
	at reitit.coercion$request_coercer$fn__7829.invoke(coercion.cljc:84) ~[app/:na]
	at reitit.coercion$coerce_request$fn__7840.invoke(coercion.cljc:113) ~[app/:na]
	at clojure.core$eval2034$fn__2035$fn__2037.invoke(core.clj:6760) ~[na:na]
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49) ~[app/:na]
	at clojure.core.protocols$fn__7839.invokeStatic(protocols.clj:75) ~[app/:na]
	at clojure.core.protocols$fn__7839.invoke(protocols.clj:75) ~[app/:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[app/:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[app/:na]
	at clojure.core$reduce.invoke(core.clj:6730) ~[app/:na]
	at clojure.core$eval2034$fn__2035.invoke(core.clj:6760) ~[na:na]
	at clojure.core.protocols$fn__7860$G__7855__7869.invoke(protocols.clj:175) ~[app/:na]
	at clojure.core$reduce_kv.invokeStatic(core.clj:6776) ~[app/:na]
	at clojure.core$reduce_kv.invoke(core.clj:6767) ~[app/:na]
	at reitit.coercion$coerce_request.invokeStatic(coercion.cljc:111) ~[app/:na]
	at reitit.coercion$coerce_request.invoke(coercion.cljc:110) ~[app/:na]
	at reitit.ring.coercion$fn__8206$fn__8208$fn__8209.invoke(coercion.cljc:33) ~[app/:na]
	at reitit.ring.coercion$fn__8216$fn__8218$fn__8219.invoke(coercion.cljc:51) ~[app/:na]
	at reitit.ring.coercion$fn__8229$fn__8231$fn__8232.invoke(coercion.cljc:66) ~[app/:na]
	at muuntaja.middleware$wrap_format$fn__9116.invoke(middleware.clj:73) ~[app/:na]
	at ring.middleware.cookies$wrap_cookies$fn__10049.invoke(cookies.clj:175) ~[app/:na]
	at ring.middleware.params$wrap_params$fn__9804.invoke(params.clj:67) ~[app/:na]
	at my-app.http.middleware.error_formatter$error_format_middleware$fn__7634.invoke(error_formatter.clj:86) ~[app/:na]
	at reitit.ring$ring_handler$fn__6043.invoke(ring.cljc:200) [app/:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) [app/:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) [app/:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) [app/:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [app/:na]
	at my-app.http.server.immutant$fn__12271$handler_wrapper__12272.invoke(immutant.clj:13) [app/:na]
	at immutant.web.internal.undertow$create_http_handler$reify__12172.handleRequest(undertow.clj:239) [app/:na]
	at org.projectodd.wunderboss.web.undertow.async.websocket.UndertowWebsocket$2.handleRequest(UndertowWebsocket.java:109) [app/:na]
	at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68) [app/:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360) [app/:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [app/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```

**Comment by ikitommi** [comment] 2018-09-26 13:31
There are many issues in this. for @valerauko the error is from route data validation, and the cause is that validation required keyword keys.

```clj
(s/def :reitit.core.coercion/kw-map (s/or :map (s/map-of keyword? any?) :spec s/spec?))
```

That's fixed now in master.

Second, the data-spec validation seems to be failing both a) normally and b) after AOT on jenkins. Would like to help, but coudn't reproduce these, so would it be possible to create a minimal repo and guide how to get the error. AOT is always complex, there could be multiple versions of same classes.

**Comment by ikitommi** [comment] 2018-09-26 13:38
btw, spec-tool's full support for latest spec alpha ( `0.2.168`) is in the master, but not released. There was a regression fix on `s/nillable`: https://github.com/metosin/spec-tools/commit/cb4b44845ae379e2b0f0f2e145aa1570fe00513b. I'll release it if that helps.

**Comment by ikitommi** [comment] 2018-09-26 14:01
pushed out `[metosin/spec-tools "0.7.2"]`, tested on latest versions.

**Comment by ikitommi** [comment] 2018-10-16 12:02
I think this is resolved, please reopen if still something fishy.

**Closed by ikitommi** 2018-10-16 12:02 UTC
Labels: More info needed
