### ISSUE TITLE
Malli schemas on nested routes with path params get merged incorrectly

### ISSUE THREAD

**Issue by jgertm** [metosin/reitit#462] opened 2021-01-04 02:02 UTC
```clojure
(reitit.core/routes
  (reitit.core/router
    ["/api/:foo"
     {:parameters {:path [:map [:foo :string]]}}
     [""]
     ["/:bar"
      {:parameters {:path [:map [:bar :string]]}}]]))
;; => [["/api/:foo" {:parameters {:path [:map [:foo :string]]}}]
;;     ["/api/:foo/:bar"
;;      {:parameters {:path [:map [:foo :string] :map [:bar :string]]}}]]

;; SHOULD BE
;; => [["/api/:foo" {:parameters {:path [:map [:foo :string]]}}]
;;     ["/api/:foo/:bar"
;;      {:parameters {:path [:map [:foo :string] [:bar :string]]}}]]
```

**Comment by jgertm** [comment] 2021-01-04 06:11
Was able to get it working with the code below. I think this shouldn't be necessary, coercions should accumulate in a fashion analogous to (path) parameters.

```clojure
(reitit.core/routes
  (reitit.core/router
    ["/api/:foo"
     {:parameters {:path [:map [:foo :string]]}}
     [""]
     ["/:bar"
      {:parameters {:path [:map [:bar :string]]}}]]
    
    {:expand   (fn [arg opts]
                 (-> arg
                   (reitit.core/expand opts)
                   (update :parameters
                     #(reduce-kv
                        (fn [params type spec]
                          (assoc params type
                            (if (or (vector? spec) (m/schema? spec))
                              (mu/to-map-syntax spec)
                              spec)))
                        (empty %)
                        %))))
     :coerce
     (fn [route opts]
       (letfn [(coerce-schema [schema]
                 (cond
                   (map? schema) (mu/from-map-syntax schema)
                   (vector? schema) (m/schema schema)
                   (m/schema? schema) schema
                   :else (throw (Exception. "unknown schema type"))))
               (coerce-parameters [data]
                 (update data :parameters
                   #(reduce-kv
                      (fn [params type spec]
                        (assoc params type (coerce-schema spec)))
                      (empty %)
                      %)))
               (coerce-responses [data]
                 (update data :responses
                   #(reduce-kv
                      (fn [responses code {:keys [body]}]
                        (assoc responses code {:body (coerce-schema body)}))
                      (empty %)
                      %)))
               (coerce-method-data [data]
                 (-> data (coerce-parameters) (coerce-responses)))
               (coerce-methods [data]
                 (reduce
                   (fn [acc method]
                     (if (contains? acc method)
                       (update acc method coerce-method-data)
                       acc))
                   data
                   reitit.ring/http-methods))
               (coerce-route [[path data]]
                 [path (-> data (coerce-parameters) (coerce-methods))])]
         (coerce-route (reitit.ring/coerce-handler route opts))))}))
```

**Comment by Deraen** [comment] 2021-02-26 20:06
Duplicate of: https://github.com/metosin/reitit/issues/422

**Closed by Deraen** 2021-02-26 20:06 UTC
