### ISSUE TITLE
The `[schema.core :as s]` Bug in version 0.3.10

### ISSUE THREAD

**Issue by chanshunli** [metosin/reitit#347] opened 2020-01-09 16:30 UTC
```txt

------ WARNING #1 - :fn-arity --------------------------------------------------
 Resource: schema/core.cljs:756:10
--------------------------------------------------------------------------------
 753 |
 754 | (clojure.core/defn map-entry-ctor [[k v :as coll]]
 755 |
 756 |          (cljs.core.MapEntry. k v))
----------------^---------------------------------------------------------------
 Wrong number of args (2) passed to cljs.core.MapEntry
--------------------------------------------------------------------------------
 757 |
 758 | ;; A schema for a single map entry.
 759 | (clojure.core/defrecord MapEntry [key-schema val-schema]
 760 |   Schema
--------------------------------------------------------------------------------

```

**Comment by miikka** [comment] 2020-01-09 18:33
It's caused by https://github.com/plumatic/schema/pull/418 which has been fixed in Schema 1.1.12. As a workaround, you can add an explicit dependency for `[prismatic/schema "1.1.12"]`. Meanwhile, we should update the dependency in [spec-tools](https://github.com/metosin/spec-tools) and then upgrade the spec-tools dependency in reitit.

**Comment by chanshunli** [comment] 2020-01-10 06:59
@miikka 

The `[prismatic/schema "1.1.12"]`  not release?

![image](https://user-images.githubusercontent.com/6021537/72132353-aea16300-33b9-11ea-9e03-9e04a7646ccb.png)

**Comment by miikka** [comment] 2020-01-10 07:32
@chanshunli The name of the Clojars artifact is *prismatic*, not *plumatic* (unlike the Github project). Here it is on Clojars: https://clojars.org/prismatic/schema/versions/1.1.12

**Comment by chanshunli** [comment] 2020-01-10 07:42
Thanks @miikka , I see 🤣

**Comment by miikka** [comment] 2020-01-10 08:14
The next version of reitit will have updated dependencies. We'll release it the next week.

**Comment by chanshunli** [comment] 2020-01-10 15:53
@miikka Good Job 👍 👍 👍 💯

**Comment by miikka** [comment] 2020-01-14 13:59
0.4.0 has been released.

**Closed by miikka** 2020-01-14 13:59 UTC
